#!/usr/bin/env php
<?php
require __DIR__ . '/vagrant/vendor/autoload.php';
// ============================================================================

use Symfony\Component\Console\Application;
use Commands\EmulsionCommand;


$application = new Application();
$application->add(new EmulsionCommand());
$application->run();